### ISSUE TITLE
쓰레드를 이용한 메인과 처리 부분 분리

### ISSUE THREAD

**Issue by kerokim** [Nerrtica/ManageSlack#14]
쓰레드를 이용해서 메인과 API 호출 및 처리 부분을 분리함.
API 호출 및 처리 부분을 분리해서 'too many error' 발생 시 앱을 종료하지 않고 해당 쓰레드만 종료시킴. 그러면 메인은 쓰레드를 부활시켜서 정상적으로 동작 할 수 있을 것 같음. (발생한 오류는 메인이 수집(또는 해당 쓰레드가 메인에게 오류 내용을 전달)해서 파일이나 콘솔 형태로 출력)

**Comment by Nerrtica** [comment]
짜주세요.

**Comment by kerokim** [comment]
앱을 종료하지 않고 재시작 효과를 주는 의견에 대해 fact_bot.py의 92번 라인에 이미
```
        while True:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            asyncio.get_event_loop().run_until_complete(execute_bot())

            time.sleep(15)
```
이런식으로 구현되어 있으므로, execute_bot()이 종료되어도 자동 재시작이 될거라고 생각됨.
그래서 58번 라인에 return 대신 break로 바꾸면 재시작 효과를 줄 수 있을거 같음.

**Comment by Nerrtica** [comment]
execute_bot 메소드를 종료하는거라 break가 아니라 return이 맞음.
저거 어제 이렇게 하면 될까 싶어서 구현해본건데 아직 에러가 안나서 되는지는 확인 못해봄
잘 되면 이 이슈는 닫겠읍니다.

**Comment by Nerrtica** [comment]
잘 되는 것으로 확인
