### ISSUE TITLE
kingname set [키워드] 띄어쓰기 잘림 현상

### ISSUE THREAD

**Issue by EnochG1** [Nerrtica/ManageSlack#35]
1. 현상이 일어난 곳
스티머즈 슬랙 #game_aceofprotectors

2. 현상
factbot kingname set 엘리트 프로텍터

명령어를 날렸을 때 

#game_aceofprotectors 채널에서 `[오늘의 엘리트 프로텍터]` 로 슬랙왕 호칭을 변경했어요.

로 팩봇이 메시지를 출력했으나
실제로 00시가 되어 슬랙왕을 출력할 때

[오늘의 엘리트]
:crown: x.pathz! (7회 / 총 12회, 지분율 58.33%)

로 출력됩니다.

**Comment by Nerrtica** [comment]
코드 상으로도 문제가 없어보이고 다시 명령어를 실행했을 때 동일한 현상이 발생하지 않아 닫겠습니다.
