### ISSUE TITLE
NeedOfKingNameStringLengthLimit

### ISSUE THREAD

**Issue by shieldnet** [Nerrtica/ManageSlack#43]
King Name을 135자 이상으로 하면, 슬랙의 글자수가 140자 제한이 있기 때문에, Exception이나 문장잘림현상이 나타날 것 같습니다

**Comment by Nerrtica** [comment]
약 4000자 수준에서 문장잘림현상이 일어나는 것을 확인했습니다만, 고치지는 않고 사용하는 유저의 재량에 맡기도록 하겠습니다.
